baseURL = 'https://hysteria.network'
title = 'Hysteria'
theme = 'hugo-book'

defaultContentLanguage = 'en'

[languages]
[languages.en]
languageName = 'English'
contentDir = 'content/en'
weight = 1
[languages.zh]
languageName = '中文'
contentDir = 'content/zh'
weight = 2

[menu]
[[menu.before]]
name = "GitHub"
url = "https://github.com/HyNetwork/hysteria"
weight = 10

[params]
BookComments = false
BookLogo = 'assets/thunder.png'

[markup.goldmark.renderer]
unsafe = true
